In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [3]:
# Create tensors with tf.constant()
scalar =tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#   number of demensions
scalar.ndim

0

In [5]:
# vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
# matrix
matrix =tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [9]:
matrix01 =tf.constant([[104.,47.,8.],[17.,130.,3.],[8.,0.,1.]], dtype=tf.float16)
matrix01

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[104.,  47.,   8.],
       [ 17., 130.,   3.],
       [  8.,   0.,   1.]], dtype=float16)>

In [10]:
matrix01.ndim

2

In [11]:
# tensor
tensor=tf.constant([[[1,2,3],[4,8,9]],[[4,5,3],[4,9,9]],[[1,2,3],[4,8,9]],[[4,5,3],[4,9,9]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 8, 9]],

       [[4, 5, 3],
        [4, 9, 9]],

       [[1, 2, 3],
        [4, 8, 9]],

       [[4, 5, 3],
        [4, 9, 9]]])>

In [12]:
tensor.ndim

3

In [13]:
chengable_tensor = tf.Variable([10,7])
unchengable_tensor = tf.constant([10,7])
chengable_tensor, unchengable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
chengable_tensor[0]
chengable_tensor[0].assign(7)
chengable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [15]:
unchengable_tensor[0] 


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [22]:
# Random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)